{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mars.gradle.plugin",
    "module": "toolkit",
    "version": "0.2.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "e3zbvqoqgnad7ffxdrnonkrnry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.0-alpha10",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.koin",
          "module": "koin-core-ext",
          "version": {
            "requires": "2.2.0-beta-1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.mars.library",
          "module": "toolkit-core-jvm",
          "version": {
            "requires": "0.2.30",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.2.31.jar",
          "url": "toolkit-0.2.31.jar",
          "size": 291884,
          "sha512": "f85345c03b0fd27e049e576b8e3daa6ea327106ee7343e8d81f65077a4472c1f465ab774b590a9c5edfdda11c63e93ea73fa4e27d4f2bcb9a6a67973824725c1",
          "sha256": "082bd572b3a7fdbebad6254c6d6c6a7fd1389c1de218ce6166bd3ecdbd9d59dc",
          "sha1": "1a162b12f08710a14b196c2b879d16ce4d045e44",
          "md5": "ce1b97ffd0d34333684418e9c19bd530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-android-gradle-plugin",
          "version": {
            "requires": "0.9.18",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.jfrog.bintray.gradle",
          "module": "gradle-bintray-plugin",
          "version": {
            "requires": "1.8.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "de.fayard.refreshVersions",
          "module": "refreshVersions",
          "version": {
            "requires": "0.9.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.0-alpha10",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.koin",
          "module": "koin-core-ext",
          "version": {
            "requires": "2.2.0-beta-1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.mars.library",
          "module": "toolkit-core-jvm",
          "version": {
            "requires": "0.2.30",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.2.31.jar",
          "url": "toolkit-0.2.31.jar",
          "size": 291884,
          "sha512": "f85345c03b0fd27e049e576b8e3daa6ea327106ee7343e8d81f65077a4472c1f465ab774b590a9c5edfdda11c63e93ea73fa4e27d4f2bcb9a6a67973824725c1",
          "sha256": "082bd572b3a7fdbebad6254c6d6c6a7fd1389c1de218ce6166bd3ecdbd9d59dc",
          "sha1": "1a162b12f08710a14b196c2b879d16ce4d045e44",
          "md5": "ce1b97ffd0d34333684418e9c19bd530"
        }
      ]
    }
  ]
}
