{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowbase.plugin",
    "module": "toolkit",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-20201227230035+0000",
      "buildId": "hhmqhid6n5f6jcncde2gdo5hiq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowbase.library",
          "module": "toolkit-core-jvm",
          "version": {
            "requires": "0.1.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "de.fayard.refreshVersions",
          "module": "refreshVersions",
          "version": {
            "requires": "0.9.7",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0-alpha03"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "7.0.0-alpha03"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.0.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.1.4.jar",
          "url": "toolkit-0.1.4.jar",
          "size": 332074,
          "sha512": "2a67f5a948b0db1ebbc5d45c5965a34e0cd0381f49da984034ebe99663a1a17b677396e589afc000e2da0c0ad9420b61d65d14943152f27072e125f0d595633f",
          "sha256": "2796d1c72cfda405d512f76cacbfba7b24fdb0b0bb25156140b628e46202b4d4",
          "sha1": "ef898973a045fe80f7b81a45420175818147031a",
          "md5": "5ec4a91f6822be5683aba5ed47fec575"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-android-gradle-plugin",
          "version": {
            "requires": "0.9.18",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.jfrog.bintray.gradle",
          "module": "gradle-bintray-plugin",
          "version": {
            "requires": "1.8.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.jakewharton.android.repackaged",
          "module": "dalvik-dx",
          "version": {
            "requires": "11.0.0_r3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowbase.library",
          "module": "toolkit-core-jvm",
          "version": {
            "requires": "0.1.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.1.4.jar",
          "url": "toolkit-0.1.4.jar",
          "size": 332074,
          "sha512": "2a67f5a948b0db1ebbc5d45c5965a34e0cd0381f49da984034ebe99663a1a17b677396e589afc000e2da0c0ad9420b61d65d14943152f27072e125f0d595633f",
          "sha256": "2796d1c72cfda405d512f76cacbfba7b24fdb0b0bb25156140b628e46202b4d4",
          "sha1": "ef898973a045fe80f7b81a45420175818147031a",
          "md5": "5ec4a91f6822be5683aba5ed47fec575"
        }
      ]
    }
  ]
}
