{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mars.gradle.plugin",
    "module": "toolkit-ui-plugin",
    "version": "0.6.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8-20200920220028+0000",
      "buildId": "ihnokyqetfhedkwe3gtlkcgd3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-ui-plugin-0.6.18.jar",
          "url": "toolkit-ui-plugin-0.6.18.jar",
          "size": 7432,
          "sha512": "fb088a4848be79057fb837008819601a1cacfcffe1db9a2d74c4cfe380ce5db21dc8a800040907498de7a36ffe78200b8741d3e5d81956eaf0694ce8d75c1f40",
          "sha256": "87e3893bcb63aa6a86ed67fc43612048ea8c82da4984aaf3b3e19d11457d4312",
          "sha1": "ef79f314f4a8f630f33d9b39c3c4eb76b10c507e",
          "md5": "640389e160a1840d139826d47c952ac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.mars.gradle.plugin",
          "module": "toolkit",
          "version": {
            "requires": "0.6.3",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-ui-plugin-0.6.18.jar",
          "url": "toolkit-ui-plugin-0.6.18.jar",
          "size": 7432,
          "sha512": "fb088a4848be79057fb837008819601a1cacfcffe1db9a2d74c4cfe380ce5db21dc8a800040907498de7a36ffe78200b8741d3e5d81956eaf0694ce8d75c1f40",
          "sha256": "87e3893bcb63aa6a86ed67fc43612048ea8c82da4984aaf3b3e19d11457d4312",
          "sha1": "ef79f314f4a8f630f33d9b39c3c4eb76b10c507e",
          "md5": "640389e160a1840d139826d47c952ac3"
        }
      ]
    }
  ]
}
